### ISSUE TITLE
Thin gaps in walls

### ISSUE THREAD

**Issue by Stirrcrazy** [Stirrcrazy/APCS-Raycaster#2]
Each non-vertical wall is composed of numerous horizontal walls, due to a bug where non-vertical walls extend infinitely across the middle of the screen once you pass their bounds. Either fix the commented out horizontal wall code, or manipulate the numerous vertical walls to fill the screen without using up too much memory.

**Comment by Stirrcrazy** [comment]
@ncbanse is assigned to this problem

**Comment by ncbanse** [comment]
ok

**Comment by Stirrcrazy** [comment]
Re-enabled bugged horizontal wall code, redesigned map to hide issues.
